var database = {
    toeholds: "TATTCC\r\n" +
    "GCTA\r\n" +
    "GTCA\r\n" +
    "TACCAA\r\n" +
    "CATCG\r\n" +
    "ACTACAC\r\n" +
    "CTCAG\r\n" +
    "CTCAATC\r\n" +
    "CCTACG\r\n" +
    "TCTCCA\r\n" +
    "CCCT\r\n" +
    "GACA\r\n" +
    "ACCT\r\n" +
    "TAGCCA\r\n" +
    "CACACA\r\n" +
    "AGAC\r\n",
    specificities: "CCCAAAACAAAACAAAACAA\r\n" +
    "CCCTTTTCTAAACTAAACAA\r\n" +
    "CCCTTTACATTACATAACAA\r\n" +
    "CCCTTATCATATCAATACAA\r\n" +
    "CCCTTAACTTAACAAATCTA\r\n" +
    "CCCTATTCAATTCAAATCAA\r\n" +
    "CCCTATACTATACAATACTA\r\n" +
    "CCCTAATCTAATCATAACTA\r\n" +
    "CCCTAAACTTATCTAAACAT\r\n" +
    "CCCATTTCAAATCAAAACTT\r\n" +
    "CCCATTACTAATCAATTCAA\r\n" +
    "CCCATATCTATACATTACAA\r\n" +
    "CCCATAACTATTCTAAACTA\r\n" +
    "CCCAATTCTTAACATATCAA\r\n" +
    "CCCAATACTATTCATAACAT\r\n" +
    "CCCAAATCTTAACTATACTA\r\n" +
    "CCTATACCTTAACTTAACAA\r\n" +
    "CCATATCCATAACTTTACAA\r\n" +
    "CCATAACCTATACTTATCAA\r\n" +
    "CCATTTCCTTTTCTTAACTA\r\n" +
    "CCATTACCATATCTTATCAT\r\n" +
    "CCAAAACCATAACATAACTT\r\n" +
    "CCAATTCCAAAACTTATCTA\r\n" +
    "CCAATACCATTACTATTCAA\r\n" +
    "CCTTAACCTTTACTTTACTT\r\n" +
    "CCTTTTCCTAATCTTTACAT\r\n" +
    "CCTTTACCAAAACATTTCAA\r\n" +
    "CCTAATCCTTATCATTACTA\r\n" +
    "CCTATTCCTTTACAAATCAT\r\n" +
    "CCAAAACAAAACCTATACAA\r\n" +
    "CCTTTACATAACCTAATCAA\r\n" +
    "CCTTATCTAAACCAATACAT\r\n" +
    "CCTTATCAATACCTATTCTA\r\n" +
    "CCTTAACAAATCCAAAACTA\r\n" +
    "CCTATTCAAATCCTTTTCAA\r\n" +
    "CCTATACAATACCATTACAT\r\n" +
    "CCTAAACTTATCCTATTCAT\r\n" +
    "CCTAAACATTACCTAAACTT\r\n" +
    "CCATTACTTAACCTTTACTA\r\n" +
    "CCATAACAATTCCAATTCAT\r\n" +
    "CCAATTCATAACCAAAACAT\r\n" +
    "CCAATACTAATCCAATACTT\r\n" +
    "CCAAATCTTAACCAATTCTA\r\n" +
    "CCAAATCAATTCCTTAACAT\r\n" +
    "CCATATCAAAACAAAACCAA\r\n" +
    "CCTATACTAAACTAAACCAA\r\n" +
    "CCTAATCTTTACATAACCAA\r\n" +
    "CCTAATCATATCTATACCAA\r\n" +
    "CCTTTTCTTATCAAATCCAA\r\n" +
    "CCTTTTCATTACAATACCTA\r\n"
}
export default database