name: Windows localhost

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK 2.1.607
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.607'
    - name: Setup .NET Core SDK 3.1.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Restore tools
      run: dotnet tool restore
    
    - name: Restore CRN dependencies
      shell: cmd
      run: msbuild CRNEngine/CRNEngineServer.sln /t:Restore
    - name: Build CRN
      shell: cmd
      run: msbuild CRNEngine/CRNEngineServer.sln /p:Configuration=Release /p:Platform=x64
    
    - name: Restore GEC dependencies
      shell: cmd
      run: msbuild ClassicGEC/ClassicGECServer.sln /t:Restore
    - name: Build GEC
      shell: cmd
      run: msbuild ClassicGEC/ClassicGECServer.sln /p:Configuration=Release /p:Platform=x64
    
    - name: Restore DSD dependencies
      shell: cmd
      run: msbuild ClassicDSD/ClassicDSDServer.sln /t:Restore
    - name: Build DSD
      shell: cmd
      run: msbuild ClassicDSD/ClassicDSDServer.sln /p:Configuration=Release /p:Platform=x64